name: Build LaTeX Report

on:
  push:
    branches: [ main ]

jobs:
  build_latex:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required to push PDF back to repo
    container:
      image: texlive/texlive:20240314-full  # Pinned for reproducibility

    env:
      REPORT_NAME: report.tex
      OUTPUT_NAME: report.pdf

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compile LaTeX document (1st pass)
        working-directory: report
        run: xelatex -interaction=nonstopmode -file-line-error $REPORT_NAME

      - name: Compile LaTeX document (2nd pass)
        working-directory: report
        run: xelatex -interaction=nonstopmode -file-line-error $REPORT_NAME

      - name: Upload PDF as artifact
        uses: actions/upload-artifact@v4
        with:
          name: Statistical_Report_PDF
          path: report/${{ env.OUTPUT_NAME }}

      - name: Upload LaTeX logs on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: LaTeX_Logs
          path: report/*.log

      - name: Prepare output files
        run: |
          mkdir -p output
          cp report/$OUTPUT_NAME output/report.pdf
          cp report/$OUTPUT_NAME output/report_latest.pdf

      - name: Commit PDF to repository
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git config --global --add safe.directory "${GITHUB_WORKSPACE}"

          git add output/report.pdf output/report_latest.pdf report/report.pdf
          git diff --staged --quiet || git commit -m "Update compiled report [skip ci]"

          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git push
